@ResumeProject.API_HostAddress = http://localhost:7211

GET {{ResumeProject.API_HostAddress}}/api/Authentication/Login
Accept: application/json
{
  "email": "admin@example.com",
  "password": "YourPassword123!"
}

###
