name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 'v8.0.x'

      - name: Publish
        run: dotnet publish ResumeProject.Blazor -c Release -o publish --self-contained false

      - name: Zip published app
        run: zip -r  my-app.zip publish/*

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ResumeWebsite
          environment_name: ResumeWebsite-env
          region: ap-southeast-1
          version_label: ${{ github.run_number }}
          deployment_package:  my-app.zip
